site_name: Synapse
pages:
- Synapse: index.md
- Architecture: architecture.md
- Plans:
  - Overview: plan.md
  - Parameters (YAML):
    - Basic: parms\yaml\basic.md
    - ForEach: parms\yaml\foreach.md
  - Parameters (JSON):
    - Basic: parms\json\basic.md
    - ForEach: parms\json\foreach.md
  - Parameters (XML):
    - Basic: parms\xml\basic.md
    - ForEach: parms\xml\foreach.md
  - Yaml: yaml.md
- CommandLine: cli.md
- Roadmap: roadmap.md
theme: readthedocs