site_name: Synapse
pages:
- Synapse: index.md
- Architecture: architecture.md
- Quick Start: quickstart.md
- Plans:
  - Overview: plans.md
  - Actions: plans/actions/detail.md
  - Parameters: plans/parms/detail.md
  - Handlers: plans/handlers.md
  - Examples:
    - Complete YAML: yaml.md
- Usage:
  - Installation/Configuration:
    - Controller/Node: run/setup.md
    - Data Access Layer: run/dal.md
#    - SSL/TLS: run/ssl.md
#    - Encrypting Plans: run/crypto.md
  - Web API:
    - Controller: run/controller.md
    - Node: run/node.md
    - Swagger: run/swagger.md
  - CommandLines:
    - Core: cli/core.md
    - Controller: cli/controller.md
    - Node: cli/node.md
    - Server: cli/server.md
  - SDK:
    - About: sdk/index.md
    - Custom Handlers: sdk/handlers.md
    - Custom Controller Interface: sdk/controller.md
- Handlers:
  - CommandLine:
    - Command Handler: handlers/commandline/command.md
    - Script Handler: handlers/commandline/script.md
  - Database:
    - SqlServer: handlers/sql/sqlserver.md
    - Oracle: handlers/sql/oracle.md
    - Odbc: handlers/sql/odbc.md
- Releases: releases.md
- Roadmap: roadmap.md
- Support: support.md
- Examples:
  - Parameters:
    - YAML:
      - Basic: plans/parms/yaml/basic.md
      - ForEach: plans/parms/yaml/foreach.md
    - JSON:
      - Basic: plans/parms/json/basic.md
      - ForEach: plans/parms/json/foreach.md
    - XML:
      - Basic: plans/parms/xml/basic.md
      - ForEach: plans/parms/xml/foreach.md
  - Complete YAML: yaml.md
theme: readthedocs