site_name: Synapse
pages:
- Synapse: index.md
- Architecture: architecture.md
- Plans:
  - Overview: plans.md
  - Actions: plans/actions/detail.md
  - Parameters: plans/parms/detail.md
  - Handlers: plans/handlers.md
  - Examples:
    - Parameters:
      - YAML:
        - Basic: plans/parms/yaml/basic.md
        - ForEach: plans/parms/yaml/foreach.md
      - JSON:
        - Basic: plans/parms/json/basic.md
        - ForEach: plans/parms/json/foreach.md
      - XML:
        - Basic: plans/parms/xml/basic.md
        - ForEach: plans/parms/xml/foreach.md
    - Complete YAML: yaml.md
- Usage:
  - Installation/Configuration:
    - Controller/Node: run/server.md
  - CommandLines:
    - Core: cli/core.md
    - Controller: cli/controller.md
    - Node: cli/node.md
  - SDK:
    - About: sdk/index.md
    - Custom Handlers: sdk/handlers.md
    - Custom Controller Interface: sdk/controller.md
- Handlers:
  - Command Handler: handlers/command.md
  - Script Handler: handlers/script.md
- Releases: releases.md
- Roadmap: roadmap.md
- Support: support.md
theme: readthedocs